### ISSUE TITLE
Boundary id's not preserved (deal.ii/Gmsh)

### ISSUE THREAD

**Issue by IudexAxiom** [martemyev/tethex#4]
Greetings,

I recently discovered your code and tested it briefly on some of my projects. I currently perform my research using deal.ii(v 9.0.0 and v9.1.1) and Gmsh(v 2.10 and v4.5.1). I was interested in your code because my professor is interested in using a semi complex domain for our research.

I used your code on a unit square domain and a unit cube domain created in Gmsh(I know I can use transfinite lines/surfaces/volumes). I then used the meshes to simulate Darcy Flow with 3 different boundary conditions.

When used on the unit square, the results were what we should expect. However, when tested on the unit cube, the results were nonsensical. 

It seemed like the boundary id's that I placed were overwritten or forgotten when I put the mesh into your code. For example, the floor of the cube has id 0, sides have id 1, and roof has id 2. (i.e. The roof has constant pressure value of 1 pascal). But when viewing the results, the roof has different values for every cell surface(i.e. three squares that made an original triangle would have values 1.01, 0.78,  and 1.28, for example), when they should be constant.

My question is: Is there something I can do to preserve id's, or maybe I am doing something wrong?
I would greatly appreciate the feedback!

**Comment by martemyev** [comment]
Hi,
There may be an issue with the id 0, as Gmsh reserves (or at least used to reserve) it for something, and it was not recommended to use it for marking entities. Please try replacing it with anything >=1. If the issue persists, please attach the .geo file, and will try and take a look.

**Comment by IudexAxiom** [comment]
Hello,

I tried replacing all the id's and I still have the same issue.
Here is the .geo file. I commented out all the transfinite parts.

I appreciate your time.



m = 10;
l = 0.1;


Point(1) = {0,0,0,l};  
Point(2) = {1,0,0,l};  
Point(3) = {1,1,0,l};  
Point(4) = {0,1,0,l}; 
 
Line(1) = {1,2};
Line(2) = {2,3};
Line(3) = {3,4};
Line(4) = {4,1};

//Transfinite Line{1:4} = m;

Line Loop(1) = {1,2,3,4};
Plane Surface(1) = {1};
//Transfinite Surface{1} = {};
//Recombine Surface{1};

Extrude {0,0,1}
{
Surface{1};
//Layers{m};
//Recombine;
}

//Transfinite Volume(1) = {};
Physical Volume(1) = {1};

Physical Surface(1) = {1};
Physical Surface(2) = {13, 17, 21, 25};
Physical Surface(3) = {26};

**Comment by martemyev** [comment]
Could you attach the input.msh that you used and output.msh that tethex produced?

**Comment by IudexAxiom** [comment]
[CubeUnstructured.msh.txt](https://github.com/martemyev/tethex/files/4135997/CubeUnstructured.msh.txt)


[CubeUnstructured_hex.msh.txt](https://github.com/martemyev/tethex/files/4135998/CubeUnstructured_hex.msh.txt)


Here are(I hope) the .msh files in .txt format. I could not upload them in .msh format.

**Comment by martemyev** [comment]
I couldn't find an obvious issue with the grids. The physical surfaces seem to stay as they are. Please see two snapshots of using Gmsh on both of them - the list of physical entities is the same, and selecting, for example, top and bottom surfaces, it can be seen that they are the same (except the grid itself, of course).
![top_bottom_tet](https://user-images.githubusercontent.com/2182432/73496597-d9774980-43b0-11ea-87c3-66f0d3fad58f.png)
![top_bottom_hex](https://user-images.githubusercontent.com/2182432/73496610-ded49400-43b0-11ea-8ce0-209afc0d8a77.png)

There may be multiple reasons why you get unexpected results, but to rule out tethex you can do the following exercise:
1. Add "Mesh.SubdivisionAlgorithm = 2;" at the end of you .geo file
2. Regenerate the mesh (in this case it will contain only hexahedra and, hence, will look pretty much exactly like what tethex produces)
3. Run it by tethex (as you did previously with tetrahedral grid) - since the grid already contains only hexahedra, tethex won't do anything except reordering vertices so that deal.II won't complain.
4. Run your calculations and compare with what you had before. If the results are still unexpected, then it's not tethex.

**Comment by IudexAxiom** [comment]
After following your exercise I did indeed still get a nonsensical solution.
It's a bummer, but at least we did ruled out tethex. This leads me to believe it may be an issue with how gmsh makes the mesh, or how deal.ii reads msh files.
 
I greatly appreciate your time and insight!
Thank you.
